### PR TITLE
(PE-31016) Bump clj-parent to 4.6.17

### PR DESCRIPTION
**Pull request by ekinanp**
Signed-off-by: Enis Inan <enis.inan@puppet.com>

### CODE REVIEW

**Comment by Magisus** [comment]
Both cells hung. We'll need to see if that reproduces outside of Travis.

**Comment by ekinanp** [comment]
Tests pass locally for me so am not sure what's up with Travis.

**Comment by Magisus** [comment]
I'll rekick the cells and see what happens.

**Comment by mwaggett** [comment]
@Magisus I did that, not sure what's happening with them

**Comment by Magisus** [comment]
One had passed after your rekick I think.

**Comment by Magisus** [comment]
They pass locally for me too. I feel like @jonathannewman ran into this a while back too and we never got anywhere on it... I'm inclined not to block this PR on figuring it out.

**Review by Magisus — APPROVED** [review]

**Pull request merged**
